
author:
    - name: Tyler Sapp
      email: sapptc@vcu.edu

date: last-modified

format:
    html:
        theme: cosmo
        toc: true
        embed-resources: true
        code-copy: true

execute:
  echo: true
  eval: true
  cache: false
